run-shell 'tmux set-option -g default-shell "$(command -v fish)"'

set -g mouse on

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

set -g default-terminal "tmux-256color"
set-option -ag terminal-overrides ",xterm-256color:Tc"


# KEYMAP
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind s display-popup -E "tmux list-sessions | fzf --reverse | cut -d: -f1 | xargs tmux switch-client -t"
bind "t" popup


# THEME
set -g status-style 'bg=#1a1b26 fg=#7aa2f7'

set -g status-left-length 20
# set -g status-left "#[fg=#1a1b26,bg=#7aa2f7,bold] #S #[default] "
set -g status-left "#[fg=#1a1b26,bg=#{?client_prefix,#444b6a,#7aa2f7},bold] #S #[default] "

set -g status-right-length 60
set -g status-right "#[fg=#414868]█#[fg=#c0caf5,bg=#414868] #(playerctl metadata --format '{{title}}') #[fg=#414868,bg=#1a1b26]"

set -g status-justify left
setw -g window-status-format "#[fg=#414868] #I:#W "
setw -g window-status-current-format "#[fg=#7aa2f7,bold][#I:#W]"

set -g pane-border-style "fg=#414868"
set -g pane-active-border-style "fg=#7aa2f7"


# RESSURECT
set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-processes 'ssh nvim agy yazi lazygit lazydocker btop'


# PLUGINS
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'

run '~/.config/tmux/plugins/tpm/tpm'
